[tool.yapf]
based_on_style = "pep8"
column_limit = 150
BLANK_LINES_AROUND_TOP_LEVEL_DEFINITION = 1
BLANK_LINE_BEFORE_NESTED_CLASS_OR_DEF = 0
COALESCE_BRACKETS = true
SPLIT_ALL_TOP_LEVEL_COMMA_SEPARATED_VALUES = false
